### ISSUE TITLE
Refactoring and update to React

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#26]
## Topic

새로운 작업: React로 변경하기에 대한 제안

## Description

* 컨텐츠 내용이 코드에 들어가 있는 것과 현재 코드의 문제들이 많음
* 따라서 React로 이전을 하며 코드를 변경하는 작업을 진행할 필요성이 제기
* React로 구성하기 전에 기존 코드에 존재하는 문제를 해결하고 넘어가는 방향으로 [논의](https://github.com/BIYN-kr/biyn-web-static/issues/26#issuecomment-565797120)
* 위 작업을 선행함으로써 추후 설계에 도움이 될 수 있음

## Todo

1. Refactor current project

- [ ] 컴포넌트에 뒤섞여 있는 static data, view 영역 분리
- [ ] 컴포넌트 구조 업데이트

2. 프로젝트 설계

- [ ] Front-end 구조 설계: 1번을 바탕으로 진행
- [ ] REST api 구축이 필요하다면 해당 내용도 설계 (who?)
- [ ] 만약 필요하다면 CMS 혹은 DB 구조 설계 `Need help`

3. 테스트 작성

- [ ] E2E 테스트 작성
- [ ] 단위 테스트 작성

4. 기타 setup

- [ ] prettier
- [ ] eslint

**Comment by plainOldCode** [comment]
React 도입에 대해서 저도 찬성합니다.
말씀하신 것처럼 현재 vue 로 작성된 코드들의 view, data 영역을 나누는 것을 제안드려봅니다.
즉 현재 상황에서 먼저 Refactoring 을 하고 React 로 가는 것은 어떠할까요?
Refactoring 을 하지 않더라도 영역이 분리되면 기존 코드를 보고 "프로젝트 설계" 부분에 유용하게 쓰일 수 있을 것 같습니다.
 
- view: *.vue 로 구성된 부분에서 json data 또는 하드코드 html 를 제외한 부분
- data: *.json 또는 *.js 또는 하드코드 html

**Comment by jennybehan** [comment]
> 말씀하신 것처럼 현재 vue 로 작성된 코드들의 view, data 영역을 나누는 것을 제안드려봅니다.
> 즉 현재 상황에서 먼저 Refactoring 을 하고 React 로 가는 것은 어떠할까요?

넵 그러면 일단 그렇게 진행해 보겠습니다.

그런 뒤 1) 현재 Vue로 구성된 프로젝트 안에서 테스트 코드를 작성하고, 2) React로 넘어가는 게 좋을까요? 
아니면 1) React로 구성한 뒤 2) 테스트를 작성하는 게 좋을까요?

**Comment by plainOldCode** [comment]
> 1) 현재 Vue로 구성된 프로젝트 안에서 테스트 코드를 작성하고, 2) React로 넘어가는 게 좋을까요?

BIYN 프로젝트의 취지가 학습과 기여를 같이 한다는 측면에서 저는 이 의견에 힘을 싣고 싶습니다.

> 그런데 view에서 설명해 주신 부분이 결국 컴포넌트겠죠?

네 그렇습니다. 그런데 이 컴포넌트가 Vue 와 React 가 다를 것이지만, json data 는 그대로 사용이 가능할 것으로 보입니다.

**Comment by jennybehan** [comment]
넵 조언 감사합니다. 당분간 이 이슈의 하위로 이슈를 생성해 보겠습니다.

**Comment by jennybehan** [comment]
이 이슈 대신 마일스톤에서 이슈 관리를 할 예정입니다.
해당 이슈 Todo에 다시 정리된 일감을 마일스톤에서 관리합니다.

**Comment by plainOldCode** [comment]
> REST api 구축이 필요하다면 해당 내용도 설계 (who?)
> 만약 필요하다면 CMS 혹은 DB 구조 설계 Need help

이 부분은 view, data 분리가 되면 다시한번 논의해서 이슈 구성해서 작업자 정하면 어떨까 합니다. 
현재 웹사이트에서 다루고 있는 data 들이 어떠한 것인이 수집한 후 (요구사항) 분석이 필요할 것 같습니다.

분석 내용에 따라서 github page 에서 사용하는 방식처럼 DB 없이도 data 구성이 가능한 스크립트를 구성하는 방식도 가능하지 않을까 합니다.
그게 아니라면 전통적인 RDBMS 를 그냥 구축하는 것도 하나의 방법일 것입니다.
그런데 보통 static 한 data 를 구성하는 경우에는 static json 을 이용하면 되기 때문에 DB 를 굳이 사용해야하는 가의 문제에 봉착합니다.
그래서 별도의 스크립트로 json 을 생성하고 그것을 사용하는 방식을 웹사이트들이 취하는 것 같습니다.

게시판의 경우는 동적인 데이터가 필요하지만 BIYN 웹 사이트들의 데이터는 한번 입력되면 거의 변경되지 않으니까요. 
하지만 프로젝트 취지중 하나인 학습에 초점을 맞춘다면 해당 작업 또한 진행해보는 것이 좋다고 생각합니다.
