### ISSUE TITLE
Google 검색시 '기본소득청' 으로 끊겨 나오는 이슈 

### ISSUE THREAD

**Issue by plainOldCode** [BIYN-kr/biyn-web-static#39]
## Topic
![Image from iOS](https://user-images.githubusercontent.com/935485/71501004-11b7d380-28ab-11ea-8c09-b0cd5f80f94f.jpg)

## Todo
- [ ] 네이버 검색 메타 확인
- [ ] 다음 검색 메타 확인
- [ ] 구글 검색 메타 확인 
- [ ] meta tag 적용하기 (vue-meta)

## 참고
현재는 CSR (Client Side Rendering ) 만 적용해보자. 

## Need help
SEO 정첵 살펴봐야함.

**Comment by plainOldCode** [comment]
> 다른 단체 일 때문에 저희것도 찾아봤는데, 
다음 포털에서는 웹사이트가 기본소득청소년네트워크 혹은 biyn 둘다 검색해도 안 나오고 네이버는 하단 내리면 biyn만 나오는데 한글단체명이 없으니 눈에 잘 안 띄네요

다음과 네이버쪽은 저희가 https 작업을 하면서 DNS 를 미국에 있는 서버를 사용하다보니 영향을 미친것 같습니다. 해당 이슈도 같이 확인해보겠습니다.

**Comment by plainOldCode** [comment]
### 추측
현재 title 은 BIYN 인데 구글의 검색 결과는 `기본소득청` 으로 으로 나오고 있다.
구글 검색 엔진의 알고리즘이 이를 추천하는 것으로 보이며 이 과정에서 `기본소득청'소'년 네트워크` 단어 안에 있는 single quote 가 rendering 되면서 뒤에서 잘리는 것 아닐까?

### 시도
기본적으로 검색엔진최적화(SEO) 가 되어있지 않다. 
이를 적용해야한다. 
- [참고할만한가이드](https://blog.usefulparadigm.com/%EA%B2%80%EC%83%89%EC%97%94%EC%A7%84%EC%B5%9C%EC%A0%81%ED%99%94-seo-%EC%89%AC%EC%9A%B4-%EA%B0%80%EC%9D%B4%EB%93%9C-f003911b0a79)
- [Google에서 인식하는 특수 태그](https://support.google.com/webmasters/answer/79812?hl=ko)

### 기대하는 바
meta tag 를 변경해서 `기본소득청'소'년 네트워크` 단어가 모두 구글검색에 표기되게 하는 것이다.

**Comment by plainOldCode** [comment]
해당 이슈는 프론트 쪽이라서 제가 혼자서 보기에는 한계가 있을 수 있어 주연님도 같이 할당하도록 하겠습니다. @jennybehan

**Comment by plainOldCode** [comment]
https://yamoo9.gitbook.io/vue-a11y-seo/seo 
참고할만한 자료를 링크합니다.

**Comment by jennybehan** [comment]
일단 메타태그를 추가하는 방식으로 진행해 보았습니다. 아래 추가해주신 vue-meta 관련 작업 이전에 한 번 해결되는지 체크해보고자 합니다.

참고 자료: https://support.google.com/webmasters/answer/35624

**Comment by jennybehan** [comment]
### #44 PR 배포 후 추가 사항

1. 여러 검색어 테스트 결과
- `기본소득청'소'년네트워크`, `기본소득청소년네트워크` 로 검색시 heroku 배포 주소가 나타나는 부분도 해결해야 할 것 같습니다. 이 부분은 따로 이슈 생성할 수도 있을 듯 합니다.
- `BIYN`이 들어간 검색어로 검색하면 naver와 동일하게 영문으로 BIYN만 나옴

2. 이전 사이트의 meta tag 체크

https://sites.google.com/site/basicincomey/ 에서 meta tag들을 확인해본 결과 다음과 같은 내용이 들어가 있었음
```
<meta name="title" content="기본소득 청'소'년 네트워크">
<meta itemprop="name" content="기본소득 청'소'년 네트워크">
<meta property="og:title" content="기본소득 청'소'년 네트워크">
<meta name="description" content="기본소득청'소'년네트워크의 웹사이트입니다.">
<meta itemprop="description" content="기본소득청'소'년네트워크의 웹사이트입니다.">
<meta id="meta-tag-description" property="og:description" content="기본소득청'소'년네트워크의 웹사이트입니다.">
```

**Comment by jennybehan** [comment]
따옴표 인식의 문제가 아닌 것으로 보아 반영이 혹시.. 느리거나, 아니면 vue-meta를 추가해야만 할 수도 있겠다는 생각이 듭니다.

**Comment by plainOldCode** [comment]
> 따옴표 인식의 문제가 아닌 것으로 보아 반영이 혹시.. 느리거나, 아니면 vue-meta를 추가해야만 할 수도 있겠다는 생각이 듭니다.

넵 이 부분은 로봇이 크롤링 해가야 알 수 있으니 시간을 두고 보면 될거 같습니다.

**Comment by jennybehan** [comment]
https://www.google.com/search?q=site%3Abiyn.kr&oq=site%3A&aqs=chrome.0.69i59j69i57j69i58j69i65l2j69i60l2.1018j0j7&sourceid=chrome&ie=UTF-8

매 페이지마다 이름이 좀 잘못되어 나오는 부분이 있네요.

넵 감사합니다~

**Comment by jennybehan** [comment]
일단 해당 문제 자체는 해결된 것으로 보고, 다른 메타 태그 및 검색 이슈 관련해서는 새로운 마일스톤과 이슈를 만들어 진행하도록 하겠습니다.
