### ISSUE TITLE
[REFACTORING] 데이터와 템플릿 영역 분리하기

### ISSUE THREAD

**Issue by jennybehan** [BIYN-kr/biyn-web-static#48]
## Category

- [ ] 운영 이슈
- [x] 신규 기능

## Description

- Issue #8 을 진행하기 전 data와 컴포넌트 템플릿 분리를 진행해야 한다.
  - [참고 스레드 항목](https://github.com/BIYN-kr/biyn-web-static/issues/8#issuecomment-568180932)
  - 위 항목으로부터 분리되어 나온 이슈입니다.
  - 기존 이슈는 테스트 작성의 건으로서 사용하고자 합니다.
  - branch: `refactoring/data-and-view`

## TODO

- [x] 화면 별로 데이터 영역 분리
  - [x] json 파일 정리 완료
    - commits: [#4e5376](https://github.com/BIYN-kr/biyn-web-static/commit/4e53764ebd3cd3326b35dde11b4a902430b3fde4), [#e6ba16](https://github.com/BIYN-kr/biyn-web-static/commit/e6ba1615671b0d2c9bf9267801f3e87940e147f9), [0b5c5b](https://github.com/BIYN-kr/biyn-web-static/commit/0b5c5b6de7fabacebf416c2d6d18dbeeec8b62ee), [dd0acc](https://github.com/BIYN-kr/biyn-web-static/commit/dd0acc27b52af9d07bad16faeb6ff36e947f636b)
  - [x] 단체소개(`/about`): teams.json 작성 후 적용 관련 부분 체크 
    - 팀 리스트(id, title, description, contact)
  - [x] [DONE] 홈, 프로젝트(`/projects`): 프로젝트 리스트(id, title, description, tags, date, image, external link)
  - [x] 뉴스레터(`/newsletter`): 뉴스레터 리스트(id, title, url)

## DEADLINE

- 2020.1.31

**Comment by jennybehan** [comment]
- [x] json 파일 정리 완료
  - commits: [#4e5376](https://github.com/BIYN-kr/biyn-web-static/commit/4e53764ebd3cd3326b35dde11b4a902430b3fde4), [#e6ba16](https://github.com/BIYN-kr/biyn-web-static/commit/e6ba1615671b0d2c9bf9267801f3e87940e147f9), [0b5c5b](https://github.com/BIYN-kr/biyn-web-static/commit/0b5c5b6de7fabacebf416c2d6d18dbeeec8b62ee), [dd0acc](https://github.com/BIYN-kr/biyn-web-static/commit/dd0acc27b52af9d07bad16faeb6ff36e947f636b)

**Comment by jennybehan** [comment]
[해당 PR](https://github.com/BIYN-kr/biyn-web-static/pull/52)을 통해 일단의 마무리를 한 것으로 생각하고 닫겠습니다.
